code/Grails/scap/grails-app/domain/scap/Afastamento.groovy
package scap

class Afastamento {

	Date dataSolic
	Date dataIniAfast
	Date dataFimAfast
	SituacaoSolicitacao situacaoSolic
	TipoAfastamento tipoAfast
	String motivoAfast
	Onus onus
	Date dataIniEvento
	Date dataFimEvento
	String nomeEvento

	//Relacionamento um-para-muitos
	//Um afastamento pertence a somente um professor
	static belongsTo = [professor:Professor, relator: Professor]

	//relacionamento bidirecional
	//Um afastamento pode possuir 0 ou muitos documentos
	static hasMany = [documentos:Documento]

	//Somente 0 ou um relator
	// static hasOne = [relator: Relator]

    static constraints = {

    	dataSolic nullable:false, blank:false
		dataIniAfast nullable:false, blank:false
		dataFimAfast nullable:false, blank:false
		dataIniEvento nullable:false, blank:false
		dataFimEvento nullable:false, blank:false
		nomeEvento nullable:false, blank:false
		professor nullable:false
		relator nullable:true, blank:true

    }

	//Modificando o modo como a representação textual é gerada
    String toString() {
        this.nomeEvento + ": " + this.professor
    }
}

code/Grails/scap/grails-app/controllers/scap/AfastamentoController.groovy
package scap

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*
import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_USER','ROLE_ADMIN'])
class AfastamentoController {

    AfastamentoService afastamentoService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond afastamentoService.list(params), model:[afastamentoCount: afastamentoService.count()]
    }

    def show(Long id) {
        respond afastamentoService.get(id)
    }

    def create() {
        respond new Afastamento(params)
    }

    def save(Afastamento afastamento) {
        if (afastamento == null) {
            notFound()
            return
        }

        try {
            afastamentoService.save(afastamento)
        } catch (ValidationException e) {
            respond afastamento.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'afastamento.label', default: 'Afastamento'), afastamento.id])
                redirect afastamento
            }
            '*' { respond afastamento, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond afastamentoService.get(id)
    }

    def update(Afastamento afastamento) {
        if (afastamento == null) {
            notFound()
            return
        }

        try {
            afastamentoService.save(afastamento)
        } catch (ValidationException e) {
            respond afastamento.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'afastamento.label', default: 'Afastamento'), afastamento.id])
                redirect afastamento
            }
            '*'{ respond afastamento, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        afastamentoService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'afastamento.label', default: 'Afastamento'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'afastamento.label', default: 'Afastamento'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def buscarPorNomeEvento(){
        def lista = []
        lista = Afastamento.findAllByNomeEventoIlike("%"+params.nome+"%")
        render(view:"index", model: [listaFiltroNomeEvento: lista]) 
    }

    def buscarPorNomeProfessor(){
        def lista = []
    
        String hql = "Select afast from Afastamento afast"+
        " where lower((concat(afast.professor.nome, ' ', afast.professor.sobrenome)))"+
        " like lower('%"+params.nome+"%')"

        lista = Afastamento.executeQuery(hql)

        render(view:"index", model: [listaFiltroNomeProfessor: lista]) 

        // lista = Afastamento.createCriteria().list{
        //     professor{
        //         or{
        //             ilike("nome","%"+params.nome+"%")
        //             ilike("sobrenome","%"+params.nome+"%")
        //         }
                
        //     }
        // }
    }

    def buscarPorDatas(){
        def lista = []

        String strDataInicial = ''+params.dataInicial_year+'-'+params.dataInicial_month+'-'+params.dataInicial_day+' 00:00:00'
        Date dataInicialSolic = Date.parse('yyyy-MM-dd HH:mm:ss', strDataInicial)

        String strDataFinal = ''+params.dataFinal_year+'-'+params.dataFinal_month+'-'+params.dataFinal_day+' 00:00:00'
        Date dataFinalSolic = Date.parse('yyyy-MM-dd HH:mm:ss', strDataFinal)
        
        lista = Afastamento.findAllByDataSolicBetween(dataInicialSolic, dataFinalSolic)

        render(view:"index", model: [listaFiltroDatas: lista]) 
    }

    def buscarPorSituacao(){
        def lista = []
        lista = Afastamento.findAllBySituacaoSolic(params.situacoes)
        render(view:"index", model: [listaFiltroSituacoes: lista]) 
    }

}

code/Grails/scap/grails-app/views/afastamento/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'afastamento.label', default: 'Afastamento')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-afastamento" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-afastamento" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.afastamento}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.afastamento}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.afastamento}" method="POST">
                <fieldset class="form">
                    <f:all bean="afastamento"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

code/Grails/scap/grails-app/views/afastamento/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'afastamento.label', default: 'Afastamento')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-afastamento" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <sec:ifNotGranted roles="ROLE_ADMIN">
                    <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                </sec:ifNotGranted>
            </ul>
        </div>
        <div id="edit-afastamento" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.afastamento}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.afastamento}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.afastamento}" method="PUT">
                <g:hiddenField name="version" value="${this.afastamento?.version}" />
                <fieldset class="form">
                    <f:all bean="afastamento"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

code/Grails/scap/grails-app/views/afastamento/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <asset:javascript src="jquery-3.3.1.min.js" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'afastamento.label', default: 'Afastamento')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-afastamento" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <sec:ifNotGranted roles="ROLE_ADMIN">
                    <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                </sec:ifNotGranted>
            </ul>
        </div>
        <div class="nav" >
            <ul>
                <li>
                    <g:form method="GET" name="formBuscarNomeProfessor" url="[controller:'Afastamento', action:'buscarPorNomeProfessor']" >
                        &nbsp; Buscar por nome do Professor:
                        <g:textField name="nome" />
                        <input type="submit" value="Buscar">
                    </g:form>
                    <br/>
                </li>   
                <li>
                    <g:form method="GET" name="formBuscarNomeEvento" url="[controller:'Afastamento', action:'buscarPorNomeEvento']" >
                        &nbsp; Buscar por nome do Evento:
                        <g:textField name="nome" />
                        <input type="submit" value="Buscar">
                    </g:form>
                </li>
            </ul>
        </div>
        <div class="nav" >    
            <ul>    
                <li>
                    &nbsp; Buscar por Data de Solicitação:
                    <g:form method="GET" name="formBuscarDatas" url="[controller:'Afastamento', action:'buscarPorDatas']" >
                        &nbsp; Data Inicial:
                        <g:datePicker name="dataInicial" value="${new Date()}" precision="day" />
                        <br/>
                        &nbsp; Data Final:&nbsp;&nbsp;
                        <g:datePicker name="dataFinal" value="${(new Date())+30}" precision="day" />
                        <input type="submit" value="Buscar">
                    </g:form>
                    <br/>
                </li>
                <li>
                    <g:form method="GET" name="formBuscarSituacao" url="[controller:'Afastamento', action:'buscarPorSituacao']" >
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        Buscar por Situação do Afastamento:
                        <g:select name="situacoes" from="${['INICIADO', 'BLOQUEADO', 'LIBERADO', 'APROVADO_DI', 'APROVADO_CT', 'APROVADO_PRPPG', 'ARQUIVADO', 'CANCELADO', 'REPROVADO']}" />
                        <input type="submit" value="Buscar">
                    </g:form>
                </li>
            </ul>
        </div>
        <div id="list-afastamento" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${afastamentoList}" />
            
            <f:table collection="${listaFiltroNomeEvento}" />

            <f:table collection="${listaFiltroNomeProfessor}" />

            <f:table collection="${listaFiltroDatas}" />

            <f:table collection="${listaFiltroSituacoes}" />

            <div class="pagination">
                <g:paginate total="${afastamentoCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

code/Grails/scap/grails-app/views/afastamento/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'afastamento.label', default: 'Afastamento')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-afastamento" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <sec:ifNotGranted roles="ROLE_ADMIN">
                    <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                </sec:ifNotGranted>
            </ul>
        </div>
        <div id="show-afastamento" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="afastamento" />
            <g:form resource="${this.afastamento}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.afastamento}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>